# Generated by Django 5.2.6 on 2025-09-22 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('appointment_type', models.CharField(choices=[('reuniao', 'Reunião'), ('ligacao', 'Ligação'), ('evento', 'Evento'), ('consulta', 'Consulta'), ('outro', 'Outro')], default='reuniao', max_length=20, verbose_name='Tipo')),
                ('priority', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=10, verbose_name='Prioridade')),
                ('status', models.CharField(choices=[('agendado', 'Agendado'), ('confirmado', 'Confirmado')], default='agendado', max_length=15, verbose_name='Status')),
                ('date', models.DateField(verbose_name='Data')),
                ('start_time', models.TimeField(verbose_name='Horário de início')),
                ('end_time', models.TimeField(verbose_name='Horário de término')),
                ('location', models.CharField(blank=True, max_length=300, verbose_name='Local')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Compromisso',
                'verbose_name_plural': 'Compromissos',
                'ordering': ['date', 'start_time'],
            },
        ),
    ]
